"""Converter for Claude Code lifecycle hooks to canonical Antigravity hooks.json."""

from __future__ import annotations

import base64
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from cc2agy.converters.mcp import read_json_for_merge, write_json_with_backup
from cc2agy.converters.variables import (
    RUNTIME_ENV_RE,
    PluginVariables,
    hook_environment,
    standalone_variables,
    substitute,
)


EVENT_MAPPING = {
    "sessionstart": "PreInvocation",
    "userpromptsubmit": "PreInvocation",
    "preinvocation": "PreInvocation",
    "postinvocation": "PostInvocation",
    "stop": "Stop",
    "pretooluse": "PreToolUse",
    "posttooluse": "PostToolUse",
}

VALID_ANTIGRAVITY_EVENTS = {
    "PreInvocation",
    "PostInvocation",
    "Stop",
    "PreToolUse",
    "PostToolUse",
}


_PLUGIN_ROOT_RE = re.compile(r"\$\{?CLAUDE_PLUGIN_ROOT\}?")
_UNQUOTED_PLUGIN_ROOT_RE = re.compile(r"(?<![\"'])\$\{?CLAUDE_PLUGIN_ROOT")

# Claude Code events whose plain-text stdout becomes model context. Antigravity only reads
# PreInvocation output as JSON ({"injectSteps": [...]}), so these run through a generated helper.
# "once" emulates SessionStart (first model invocation of a conversation, invocationNum == 0).
CONTEXT_EVENT_MODES = {
    "sessionstart": "once",
    "userpromptsubmit": "always",
}
CONTEXT_HELPER_DIR = "cc2agy_hooks"
CONTEXT_HELPER_FILE = "hook_runner.py"
CONTEXT_HELPER_SOURCE = '''"""Generated by cc2agy: runs a Claude Code hook the way Claude Code would, under Antigravity.

Usage: hook_runner.py <base64-json-spec>
The spec holds "mode", "command", "args" (a list for exec form, null for shell form) and "env".
- mode "plain": runs the hook and passes its output and exit code through.
- mode "once": runs only on the first model invocation of a conversation (invocationNum == 0),
  emulating Claude Code's SessionStart; stdout becomes an injected ephemeral message.
- mode "always": runs before every model invocation; stdout becomes an injected message.
The process receives the spec's environment (CLAUDE_PLUGIN_ROOT, CLAUDE_PLUGIN_DATA,
CLAUDE_PLUGIN_OPTION_<KEY>) plus CLAUDE_PROJECT_DIR, taken from the first Antigravity
workspace path; ${CLAUDE_PROJECT_DIR} in the command and args is replaced with it.
Input and output pass through as UTF-8 bytes, whatever the system code page.
"""
import base64
import json
import os
import re
import subprocess
import sys


def main():
    spec = json.loads(base64.urlsafe_b64decode(sys.argv[1]).decode("utf-8"))
    mode = spec.get("mode", "plain")
    raw_input = sys.stdin.buffer.read()
    try:
        payload = json.loads(raw_input.decode("utf-8")) if raw_input.strip() else {}
    except ValueError:
        payload = {}
    if mode == "once" and payload.get("invocationNum", 0) != 0:
        print("{}")
        return 0

    workspaces = payload.get("workspacePaths") or []
    project_dir = workspaces[0] if workspaces else os.getcwd()
    env = dict(os.environ)
    env.update(spec.get("env") or {})
    env["CLAUDE_PROJECT_DIR"] = project_dir

    def fill(text):
        return re.sub(r"\\$\\{?CLAUDE_PROJECT_DIR\\}?", lambda _: project_dir, text)

    command = fill(spec["command"])
    args = spec.get("args")
    try:
        result = subprocess.run(
            [command] + [fill(a) for a in args] if args is not None else command,
            shell=args is None, input=raw_input, capture_output=True, env=env,
        )
    except OSError as e:
        sys.stderr.write(f"cc2agy hook runner: cannot start '{command}': {e}\\n")
        return 1
    if result.stderr:
        sys.stderr.buffer.write(result.stderr)
    if mode == "plain":
        sys.stdout.buffer.write(result.stdout)
        return result.returncode
    output = result.stdout.decode("utf-8", errors="replace").strip()
    print(json.dumps({"injectSteps": [{"ephemeralMessage": output}]} if output else {}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _python_command() -> str:
    """Interpreter name used to run the generated helper (resolved through PATH)."""
    return "python" if sys.platform == "win32" else "python3"


def _shell_quote(path: str) -> str:
    return f'"{path}"' if " " in path else path


def sanitize_hook_command(command: str, plugin_root: Optional[Path] = None) -> str:
    """Replace ${CLAUDE_PLUGIN_ROOT} in a hook command.

    With plugin_root, the variable becomes that absolute folder (forward slashes, as Claude
    Code substitutes on Windows): Antigravity documents neither the hook working directory
    nor a plugin-root variable, so only an absolute path is reliable. Without plugin_root,
    the legacy relative form ('.') is kept.
    """
    if not command:
        return command
    root = plugin_root.as_posix() if plugin_root is not None else "."
    return _PLUGIN_ROOT_RE.sub(lambda _: root, command)


def _variables_for(plugin_root: Optional[Path], variables: Optional[PluginVariables]) -> PluginVariables:
    """Variables for a conversion; without any, ${CLAUDE_PLUGIN_ROOT} keeps the legacy '.' form."""
    if variables is not None:
        return variables
    return PluginVariables(root=plugin_root if plugin_root is not None else Path("."))


def _build_handler(
    item: Dict[str, Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    context_mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> Dict[str, Any]:
    """Build one Antigravity handler from a Claude Code handler object.

    A hook runs through the generated hook runner when Antigravity cannot run it as is: a
    context hook (SessionStart, UserPromptSubmit), an exec-form hook ('args', which must reach
    the program unquoted), or a hook that needs the environment Claude Code exports
    (CLAUDE_PROJECT_DIR, CLAUDE_PLUGIN_OPTION_<KEY>, or plugin scripts reading CLAUDE_*).
    """
    variables = _variables_for(plugin_root, variables)
    raw_command = str(item.get("command", ""))
    raw_args = item.get("args")
    exec_form = isinstance(raw_args, list)
    root = variables.root.as_posix()
    if not exec_form and " " in root and _UNQUOTED_PLUGIN_ROOT_RE.search(raw_command):
        warnings.append(
            f"Hook command uses ${{CLAUDE_PLUGIN_ROOT}} without quotes and the plugin path contains "
            f"spaces ('{root}'); quote it in the source command: {raw_command}"
        )
    where = "hook_exec" if exec_form else "hook_shell"
    command = substitute(raw_command, variables, where, warnings)
    args = [substitute(str(a), variables, "hook_exec", warnings) for a in raw_args] if exec_form else None

    raw_text = " ".join([raw_command, *(str(a) for a in raw_args or [])])
    needs_runner = (
        context_mode is not None
        or exec_form
        or variables.scripts_read_env
        or bool(RUNTIME_ENV_RE.search(raw_text))
    )
    if needs_runner and helper_dir is not None:
        spec = {
            "mode": context_mode or "plain",
            "command": command,
            "args": args,
            "env": hook_environment(variables, warnings),
        }
        helper = (helper_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE).as_posix()
        encoded = base64.urlsafe_b64encode(json.dumps(spec).encode("utf-8")).decode("ascii")
        command = f"{_python_command()} {_shell_quote(helper)} {encoded}"
    elif exec_form:
        command = " ".join([_shell_quote(command), *(_shell_quote(a) for a in args)])
        warnings.append(f"Exec-form hook converted to a shell command without the hook runner: {command}")

    handler: Dict[str, Any] = {
        "type": item.get("type", "command"),
        "command": command,
    }
    if "timeout" in item and isinstance(item["timeout"], int):
        handler["timeout"] = item["timeout"]
    return handler


def _is_startup_matcher(matcher: Any) -> bool:
    """SessionStart groups apply on startup unless their matcher excludes it."""
    if not matcher or matcher == "*":
        return True
    return bool(re.search(r"\bstartup\b", str(matcher)))


def extract_flat_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    context_mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> List[Dict[str, Any]]:
    """Extract flat handler objects from potentially nested Claude Code hooks lists."""
    handlers: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        if context_mode == "once" and not _is_startup_matcher(item.get("matcher")):
            warnings.append(
                f"Skipped SessionStart hooks with matcher '{item.get('matcher')}': Antigravity has no "
                "resume, clear, compact or fork event."
            )
            continue
        # Claude Code often nests handlers inside {"hooks": [...]}
        if "hooks" in item and isinstance(item["hooks"], list):
            for sub_item in item["hooks"]:
                if isinstance(sub_item, dict):
                    handlers.append(_build_handler(sub_item, warnings, plugin_root, context_mode, helper_dir, variables))
        elif "command" in item:
            handlers.append(_build_handler(item, warnings, plugin_root, context_mode, helper_dir, variables))
        else:
            warnings.append(f"Ignored unrecognized hook handler structure: {item}")
    return handlers


def sanitize_matcher(matcher: str) -> str:
    """Map Claude tool names in matchers to Antigravity tool names."""
    if not matcher or matcher == "*":
        return matcher
    mapping = [
        (r"\bMultiEdit\b", "multi_replace_file_content"),
        # Antigravity splits edits into two tools (matchers are regular expressions)
        (r"\bEdit\b", "(?:replace_file_content|multi_replace_file_content)"),
        (r"\bWrite\b", "write_to_file"),
        (r"\bBash\b", "run_command"),
        (r"\bRead\b", "view_file"),
    ]
    cleaned = matcher
    for pat, repl in mapping:
        cleaned = re.sub(pat, repl, cleaned)
    return cleaned


def extract_grouped_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> List[Dict[str, Any]]:
    """Extract grouped matcher handler objects for PreToolUse and PostToolUse."""
    groups: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        matcher = sanitize_matcher(item.get("matcher", "*"))
        sub_hooks = item.get("hooks", [])
        handlers: List[Dict[str, Any]] = []
        if isinstance(sub_hooks, list):
            for h in sub_hooks:
                if isinstance(h, dict) and "command" in h:
                    handlers.append(_build_handler(h, warnings, plugin_root, helper_dir=helper_dir, variables=variables))
        elif "command" in item:
            handlers.append(_build_handler(item, warnings, plugin_root, helper_dir=helper_dir, variables=variables))

        if handlers:
            groups.append({
                "matcher": matcher,
                "hooks": handlers,
            })
    return groups


def convert_hooks_data(
    raw_data: Dict[str, Any],
    plugin_name: str = "plugin",
    plugin_root: Optional[Path] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> Tuple[Dict[str, Any], List[str]]:
    """Convert raw Claude Code hooks dictionary into Antigravity canonical hooks dictionary.

    Args:
        plugin_root: Absolute folder that ${CLAUDE_PLUGIN_ROOT} stands for (where the
            plugin's scripts live). When omitted, the legacy relative form is used.
        helper_dir: Folder that will hold hooks.json and the generated hook runner.
            When omitted, no command is wrapped.
        variables: What Claude Code plugin variables and userConfig become (overrides plugin_root).
    """
    warnings: List[str] = []

    # If data has a top-level "hooks" wrapper: {"hooks": { ... }}
    hooks_dict = raw_data.get("hooks", raw_data)
    if not isinstance(hooks_dict, dict):
        warnings.append("Root hooks entry is not a dictionary.")
        hooks_dict = {}

    converted_events: Dict[str, Any] = {}

    for raw_event, event_content in hooks_dict.items():
        mapped_event = EVENT_MAPPING.get(raw_event.lower())
        if not mapped_event:
            warnings.append(f"Skipped unsupported hook event: '{raw_event}'.")
            continue

        if raw_event.lower() != mapped_event.lower():
            warnings.append(f"Mapped event '{raw_event}' -> '{mapped_event}'.")

        if not isinstance(event_content, list):
            warnings.append(f"Hook event '{raw_event}' does not contain a list of handlers.")
            continue

        if mapped_event in ("PreToolUse", "PostToolUse"):
            groups = extract_grouped_handlers(event_content, warnings, plugin_root, helper_dir, variables)
            if groups:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(groups)
                else:
                    converted_events[mapped_event] = groups
        else:
            context_mode = CONTEXT_EVENT_MODES.get(raw_event.lower())
            if context_mode == "always":
                warnings.append(
                    f"'{raw_event}' hooks run before every model invocation in Antigravity, "
                    "not once per user message."
                )
            if context_mode is not None and helper_dir is None:
                warnings.append(
                    f"'{raw_event}' output is not converted to Antigravity context without a destination folder."
                )
            handlers = extract_flat_handlers(event_content, warnings, plugin_root, context_mode, helper_dir, variables)
            if handlers:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(handlers)
                else:
                    converted_events[mapped_event] = handlers

    hook_id = f"{plugin_name}-hooks"
    final_hooks_config = {
        hook_id: converted_events
    }
    return final_hooks_config, warnings


def convert_hooks_file(
    source_path: Path,
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    merge: bool = False,
) -> Tuple[Path, List[str]]:
    """Read source hooks.json, convert to Antigravity format, and write to dest_dir/hooks.json.

    merge: add the converted hook group to an existing dest_dir/hooks.json (see write_hooks_data).
    """
    source_path = source_path.resolve()
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"

    if dest_file.exists() and not overwrite and not merge:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    try:
        with open(source_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except Exception as e:
        raise ValueError(f"Failed to read/parse hooks JSON from {source_path}: {e}")

    variables = standalone_variables(source_path, dest_dir, scan_scripts=True)
    return write_hooks_data(
        raw_data, dest_dir, plugin_name=plugin_name, overwrite=overwrite, variables=variables, merge=merge
    )


def write_hooks_data(
    raw_data: Dict[str, Any],
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    plugin_root: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
    merge: bool = False,
) -> Tuple[Path, List[str]]:
    """Convert already-loaded Claude Code hooks data and write it to dest_dir/hooks.json.

    plugin_root defaults to dest_dir (a packaged plugin keeps its scripts beside hooks.json);
    variables, when given, takes precedence. The hook runner is written to
    dest_dir/cc2agy_hooks/ when any hook needs it.

    With merge, an existing hooks.json is kept: the converted group ('<plugin_name>-hooks')
    is added beside the groups already there, which are never touched; a group with the same
    name needs overwrite. The previous file is saved as hooks.json.cc2agy.bak.
    """
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"
    plugin_root = (plugin_root or dest_dir).resolve()

    existing: Optional[Dict[str, Any]] = None
    if merge and dest_file.exists():
        existing = read_json_for_merge(dest_file)
    elif dest_file.exists() and not overwrite:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    converted_config, warnings = convert_hooks_data(
        raw_data, plugin_name=plugin_name, plugin_root=plugin_root, helper_dir=dest_dir, variables=variables
    )

    dest_dir.mkdir(parents=True, exist_ok=True)
    if existing is not None:
        for hook_id in converted_config:
            if hook_id in existing and not overwrite:
                raise FileExistsError(f"Hook group '{hook_id}' already exists in {dest_file}")
        existing.update(converted_config)
        write_json_with_backup(dest_file, existing)
    else:
        with open(dest_file, "w", encoding="utf-8") as f:
            json.dump(converted_config, f, indent=2, ensure_ascii=False)
            f.write("\n")

    helper_file = dest_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE
    if helper_file.as_posix() in json.dumps(converted_config, ensure_ascii=False):
        helper_file.parent.mkdir(parents=True, exist_ok=True)
        helper_file.write_text(CONTEXT_HELPER_SOURCE, encoding="utf-8")

    return dest_file, warnings
