"""Converter for Claude Code lifecycle hooks to canonical Antigravity hooks.json."""

from __future__ import annotations

import base64
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


EVENT_MAPPING = {
    "sessionstart": "PreInvocation",
    "userpromptsubmit": "PreInvocation",
    "preinvocation": "PreInvocation",
    "postinvocation": "PostInvocation",
    "stop": "Stop",
    "pretooluse": "PreToolUse",
    "posttooluse": "PostToolUse",
}

VALID_ANTIGRAVITY_EVENTS = {
    "PreInvocation",
    "PostInvocation",
    "Stop",
    "PreToolUse",
    "PostToolUse",
}


_PLUGIN_ROOT_RE = re.compile(r"\$\{?CLAUDE_PLUGIN_ROOT\}?")
_UNQUOTED_PLUGIN_ROOT_RE = re.compile(r"(?<![\"'])\$\{?CLAUDE_PLUGIN_ROOT")

# Claude Code events whose plain-text stdout becomes model context. Antigravity only reads
# PreInvocation output as JSON ({"injectSteps": [...]}), so these run through a generated helper.
# "once" emulates SessionStart (first model invocation of a conversation, invocationNum == 0).
CONTEXT_EVENT_MODES = {
    "sessionstart": "once",
    "userpromptsubmit": "always",
}
CONTEXT_HELPER_DIR = "cc2agy_hooks"
CONTEXT_HELPER_FILE = "context_hook.py"
CONTEXT_HELPER_SOURCE = '''"""Generated by cc2agy: runs a Claude Code context hook as an Antigravity PreInvocation hook.

Usage: context_hook.py <once|always> <base64-command>
- once: runs the command only on the first model invocation of a conversation
  (invocationNum == 0), emulating Claude Code's SessionStart.
- always: runs the command before every model invocation.
The command's plain-text stdout becomes an Antigravity injected ephemeral message.
"""
import base64
import json
import subprocess
import sys


def main():
    mode, encoded = sys.argv[1], sys.argv[2]
    raw_input = sys.stdin.read()
    try:
        payload = json.loads(raw_input) if raw_input.strip() else {}
    except ValueError:
        payload = {}
    if mode == "once" and payload.get("invocationNum", 0) != 0:
        print("{}")
        return 0

    command = base64.urlsafe_b64decode(encoded).decode("utf-8")
    result = subprocess.run(
        command, shell=True, input=raw_input, capture_output=True,
        text=True, encoding="utf-8", errors="replace",
    )
    if result.stderr:
        sys.stderr.write(result.stderr)
    output = result.stdout.strip()
    print(json.dumps({"injectSteps": [{"ephemeralMessage": output}]} if output else {}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _python_command() -> str:
    """Interpreter name used to run the generated helper (resolved through PATH)."""
    return "python" if sys.platform == "win32" else "python3"


def _shell_quote(path: str) -> str:
    return f'"{path}"' if " " in path else path


def sanitize_hook_command(command: str, plugin_root: Optional[Path] = None) -> str:
    """Replace ${CLAUDE_PLUGIN_ROOT} in a hook command.

    With plugin_root, the variable becomes that absolute folder (forward slashes, as Claude
    Code substitutes on Windows): Antigravity documents neither the hook working directory
    nor a plugin-root variable, so only an absolute path is reliable. Without plugin_root,
    the legacy relative form ('.') is kept.
    """
    if not command:
        return command
    root = plugin_root.as_posix() if plugin_root is not None else "."
    return _PLUGIN_ROOT_RE.sub(lambda _: root, command)


def _build_handler(
    item: Dict[str, Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    context_mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Build one Antigravity handler from a Claude Code handler object."""
    raw_command = str(item.get("command", ""))
    if plugin_root is not None and " " in plugin_root.as_posix() and _UNQUOTED_PLUGIN_ROOT_RE.search(raw_command):
        warnings.append(
            f"Hook command uses ${{CLAUDE_PLUGIN_ROOT}} without quotes and the plugin path contains "
            f"spaces ('{plugin_root.as_posix()}'); quote it in the source command: {raw_command}"
        )
    command = sanitize_hook_command(raw_command, plugin_root)

    if context_mode is not None and helper_dir is not None:
        helper = (helper_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE).as_posix()
        encoded = base64.urlsafe_b64encode(command.encode("utf-8")).decode("ascii")
        command = f"{_python_command()} {_shell_quote(helper)} {context_mode} {encoded}"

    handler: Dict[str, Any] = {
        "type": item.get("type", "command"),
        "command": command,
    }
    if "timeout" in item and isinstance(item["timeout"], int):
        handler["timeout"] = item["timeout"]
    return handler


def _is_startup_matcher(matcher: Any) -> bool:
    """SessionStart groups apply on startup unless their matcher excludes it."""
    if not matcher or matcher == "*":
        return True
    return bool(re.search(r"\bstartup\b", str(matcher)))


def extract_flat_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    context_mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
) -> List[Dict[str, Any]]:
    """Extract flat handler objects from potentially nested Claude Code hooks lists."""
    handlers: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        if context_mode == "once" and not _is_startup_matcher(item.get("matcher")):
            warnings.append(
                f"Skipped SessionStart hooks with matcher '{item.get('matcher')}': Antigravity has no "
                "resume, clear, compact or fork event."
            )
            continue
        # Claude Code often nests handlers inside {"hooks": [...]}
        if "hooks" in item and isinstance(item["hooks"], list):
            for sub_item in item["hooks"]:
                if isinstance(sub_item, dict):
                    handlers.append(_build_handler(sub_item, warnings, plugin_root, context_mode, helper_dir))
        elif "command" in item:
            handlers.append(_build_handler(item, warnings, plugin_root, context_mode, helper_dir))
        else:
            warnings.append(f"Ignored unrecognized hook handler structure: {item}")
    return handlers


def sanitize_matcher(matcher: str) -> str:
    """Map Claude tool names in matchers to Antigravity tool names."""
    if not matcher or matcher == "*":
        return matcher
    mapping = [
        (r"\bMultiEdit\b", "multi_replace_file_content"),
        # Antigravity splits edits into two tools (matchers are regular expressions)
        (r"\bEdit\b", "(?:replace_file_content|multi_replace_file_content)"),
        (r"\bWrite\b", "write_to_file"),
        (r"\bBash\b", "run_command"),
        (r"\bRead\b", "view_file"),
    ]
    cleaned = matcher
    for pat, repl in mapping:
        cleaned = re.sub(pat, repl, cleaned)
    return cleaned


def extract_grouped_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
) -> List[Dict[str, Any]]:
    """Extract grouped matcher handler objects for PreToolUse and PostToolUse."""
    groups: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        matcher = sanitize_matcher(item.get("matcher", "*"))
        sub_hooks = item.get("hooks", [])
        handlers: List[Dict[str, Any]] = []
        if isinstance(sub_hooks, list):
            for h in sub_hooks:
                if isinstance(h, dict) and "command" in h:
                    handlers.append(_build_handler(h, warnings, plugin_root))
        elif "command" in item:
            handlers.append(_build_handler(item, warnings, plugin_root))

        if handlers:
            groups.append({
                "matcher": matcher,
                "hooks": handlers,
            })
    return groups


def convert_hooks_data(
    raw_data: Dict[str, Any],
    plugin_name: str = "plugin",
    plugin_root: Optional[Path] = None,
    helper_dir: Optional[Path] = None,
) -> Tuple[Dict[str, Any], List[str]]:
    """Convert raw Claude Code hooks dictionary into Antigravity canonical hooks dictionary.

    Args:
        plugin_root: Absolute folder that ${CLAUDE_PLUGIN_ROOT} stands for (where the
            plugin's scripts live). When omitted, the legacy relative form is used.
        helper_dir: Folder that will hold hooks.json and the generated context helper.
            When omitted, SessionStart/UserPromptSubmit commands are not wrapped.
    """
    warnings: List[str] = []

    # If data has a top-level "hooks" wrapper: {"hooks": { ... }}
    hooks_dict = raw_data.get("hooks", raw_data)
    if not isinstance(hooks_dict, dict):
        warnings.append("Root hooks entry is not a dictionary.")
        hooks_dict = {}

    converted_events: Dict[str, Any] = {}

    for raw_event, event_content in hooks_dict.items():
        mapped_event = EVENT_MAPPING.get(raw_event.lower())
        if not mapped_event:
            warnings.append(f"Skipped unsupported hook event: '{raw_event}'.")
            continue

        if raw_event.lower() != mapped_event.lower():
            warnings.append(f"Mapped event '{raw_event}' -> '{mapped_event}'.")

        if not isinstance(event_content, list):
            warnings.append(f"Hook event '{raw_event}' does not contain a list of handlers.")
            continue

        if mapped_event in ("PreToolUse", "PostToolUse"):
            groups = extract_grouped_handlers(event_content, warnings, plugin_root)
            if groups:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(groups)
                else:
                    converted_events[mapped_event] = groups
        else:
            context_mode = CONTEXT_EVENT_MODES.get(raw_event.lower())
            if context_mode == "always":
                warnings.append(
                    f"'{raw_event}' hooks run before every model invocation in Antigravity, "
                    "not once per user message."
                )
            if context_mode is not None and helper_dir is None:
                warnings.append(
                    f"'{raw_event}' output is not converted to Antigravity context without a destination folder."
                )
            handlers = extract_flat_handlers(event_content, warnings, plugin_root, context_mode, helper_dir)
            if handlers:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(handlers)
                else:
                    converted_events[mapped_event] = handlers

    hook_id = f"{plugin_name}-hooks"
    final_hooks_config = {
        hook_id: converted_events
    }
    return final_hooks_config, warnings


def convert_hooks_file(
    source_path: Path,
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
) -> Tuple[Path, List[str]]:
    """Read source hooks.json, convert to Antigravity format, and write to dest_dir/hooks.json."""
    source_path = source_path.resolve()
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"

    if dest_file.exists() and not overwrite:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    try:
        with open(source_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except Exception as e:
        raise ValueError(f"Failed to read/parse hooks JSON from {source_path}: {e}")

    # Scripts are not copied in a standalone hooks conversion, so ${CLAUDE_PLUGIN_ROOT}
    # points to the source plugin folder (hooks/hooks.json lives one level below it).
    plugin_root = source_path.parent
    if plugin_root.name.lower() in ("hooks", ".claude"):
        plugin_root = plugin_root.parent

    return write_hooks_data(
        raw_data, dest_dir, plugin_name=plugin_name, overwrite=overwrite, plugin_root=plugin_root
    )


def write_hooks_data(
    raw_data: Dict[str, Any],
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    plugin_root: Optional[Path] = None,
) -> Tuple[Path, List[str]]:
    """Convert already-loaded Claude Code hooks data and write it to dest_dir/hooks.json.

    plugin_root defaults to dest_dir (a packaged plugin keeps its scripts beside hooks.json).
    The context helper script is written to dest_dir/cc2agy_hooks/ when any hook needs it.
    """
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"
    plugin_root = (plugin_root or dest_dir).resolve()

    if dest_file.exists() and not overwrite:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    converted_config, warnings = convert_hooks_data(
        raw_data, plugin_name=plugin_name, plugin_root=plugin_root, helper_dir=dest_dir
    )

    dest_dir.mkdir(parents=True, exist_ok=True)
    with open(dest_file, "w", encoding="utf-8") as f:
        json.dump(converted_config, f, indent=2, ensure_ascii=False)
        f.write("\n")

    helper_file = dest_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE
    if helper_file.as_posix() in json.dumps(converted_config, ensure_ascii=False):
        helper_file.parent.mkdir(parents=True, exist_ok=True)
        helper_file.write_text(CONTEXT_HELPER_SOURCE, encoding="utf-8")

    return dest_file, warnings
