"""Converter for Claude Code lifecycle hooks to canonical Antigravity hooks.json."""

from __future__ import annotations

import base64
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from cc2agy.converters.mcp import read_json_for_merge, write_json_with_backup
from cc2agy.converters.variables import (
    RUNTIME_ENV_RE,
    PluginVariables,
    hook_environment,
    standalone_variables,
    substitute,
)


EVENT_MAPPING = {
    "sessionstart": "PreInvocation",
    "userpromptsubmit": "PreInvocation",
    "preinvocation": "PreInvocation",
    "postinvocation": "PostInvocation",
    "stop": "Stop",
    "pretooluse": "PreToolUse",
    "posttooluse": "PostToolUse",
}

VALID_ANTIGRAVITY_EVENTS = {
    "PreInvocation",
    "PostInvocation",
    "Stop",
    "PreToolUse",
    "PostToolUse",
}


_PLUGIN_ROOT_RE = re.compile(r"\$\{?CLAUDE_PLUGIN_ROOT\}?")
_UNQUOTED_PLUGIN_ROOT_RE = re.compile(r"(?<![\"'])\$\{?CLAUDE_PLUGIN_ROOT")

# Claude Code events whose plain-text stdout becomes model context. Antigravity only reads
# PreInvocation output as JSON ({"injectSteps": [...]}), so these run through a generated helper.
# "once" emulates SessionStart (first model invocation of a conversation, tracked by a marker file).
CONTEXT_EVENT_MODES = {
    "sessionstart": "once",
    "userpromptsubmit": "always",
}
# Events whose stdout Antigravity parses strictly (an unknown field or plain text fails the
# hook and blocks the tool): every hook of these events runs through the helper, which
# translates Claude Code's exit codes and JSON output into Antigravity's.
OUTPUT_EVENT_MODES = {
    "pretooluse": "pre_tool",
    "posttooluse": "post_tool",
    "stop": "stop",
}
# Claude Code project settings files whose "hooks" key holds project hooks, in precedence
# order (settings.local.json overrides settings.json); other settings keys are not converted
SETTINGS_FILES = ("settings.json", "settings.local.json")
_SETTINGS_HOOK_KEYS = {"hooks", "disableAllHooks", "$schema"}
CONTEXT_HELPER_DIR = "cc2agy_hooks"
CONTEXT_HELPER_FILE = "hook_runner.py"
CONTEXT_HELPER_SOURCE = '''"""Generated by cc2agy: runs a Claude Code hook the way Claude Code would, under Antigravity.

Usage: hook_runner.py <base64-json-spec>
The spec holds "mode", "command", "args" (a list for exec form, null for shell form) and "env".
- mode "plain": runs the hook and passes its output and exit code through.
- mode "once": runs only on the first model invocation of a conversation (a marker file per
  conversation and hook; invocationNum restarts at 0 on every execution), emulating Claude
  Code's SessionStart; stdout becomes an injected ephemeral message.
- modes "once" and "stop" skip subagent conversations, as Claude Code does, detected by an
  undocumented file Antigravity writes when it creates a subagent.
- mode "always": runs before every model invocation; stdout becomes an injected message.
- mode "pre_tool": Claude Code's PreToolUse result (exit code 2, permissionDecision, the
  deprecated decision field) becomes Antigravity's {"decision": ..., "reason": ...}.
- mode "stop": a Claude Code request to keep working (exit code 2 or decision "block")
  becomes {"decision": "continue", "reason": ...}; stop_hook_active is emulated with a marker
  file per conversation and hook in the system temp folder.
- mode "post_tool": the hook runs for its side effects; Antigravity has no equivalent for
  what Claude Code reads from its output, so nothing is printed.
In the modes named after Claude Code events, the hook's input gets Claude Code's fields
(session_id, transcript_path, cwd, hook_event_name, tool_name, tool_input, tool_response,
stop_hook_active) on top of Antigravity's; only tools with confirmed arguments are renamed.
In every mode but "plain" the runner exits 0: Claude Code ignores errors other than exit 2,
while Antigravity fails the hook (and blocks the tool) on any other code.
The process receives the spec's environment (CLAUDE_PLUGIN_ROOT, CLAUDE_PLUGIN_DATA,
CLAUDE_PLUGIN_OPTION_<KEY>) plus CLAUDE_PROJECT_DIR, taken from the first Antigravity
workspace path; ${CLAUDE_PROJECT_DIR} in the command and args is replaced with it. The hook
runs in that folder, as Claude Code runs hooks in the session folder.
Input and output pass through as UTF-8 bytes, whatever the system code page.
"""
import base64
import glob
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

DECISIONS = {"allow": "allow", "deny": "deny", "ask": "ask", "approve": "allow", "block": "deny"}
EVENT_NAMES = {"once": "SessionStart", "always": "UserPromptSubmit", "pre_tool": "PreToolUse",
               "post_tool": "PostToolUse", "stop": "Stop"}
# Antigravity tools whose arguments were confirmed (documentation and a real run) and their
# Claude Code names; any other tool keeps its Antigravity name and arguments
TOOL_NAMES = {"view_file": "Read", "write_to_file": "Write", "replace_file_content": "Edit",
              "run_command": "Bash", "read_url_content": "WebFetch", "search_web": "WebSearch"}
TOOL_ARGS = {
    "view_file": {"AbsolutePath": "file_path"},
    "write_to_file": {"TargetFile": "file_path", "CodeContent": "content"},
    "replace_file_content": {"TargetFile": "file_path", "TargetContent": "old_string",
                             "ReplacementContent": "new_string", "AllowMultiple": "replace_all"},
    "run_command": {"CommandLine": "command"},
    "read_url_content": {"Url": "url"},
    "search_web": {"query": "query"},
}


def note(message):
    print("cc2agy hook runner: " + message, file=sys.stderr)


def claude_json(stdout):
    """The hook's JSON output, read as Claude Code does (only text starting with { and ending with })."""
    text = stdout.strip()
    if not (text.startswith("{") and text.endswith("}")):
        return None
    try:
        data = json.loads(text)
    except ValueError:
        return None
    return data if isinstance(data, dict) else None


def specific(data):
    value = (data or {}).get("hookSpecificOutput")
    return value if isinstance(value, dict) else {}


def join(*parts):
    return " ".join(p.strip() for p in parts if isinstance(p, str) and p.strip())


def pre_tool_decision(returncode, stdout, stderr):
    """Antigravity PreToolUse output for a Claude Code PreToolUse result (None: no decision)."""
    data = claude_json(stdout)
    extra = specific(data)
    value = extra.get("permissionDecision", (data or {}).get("decision"))
    decision = DECISIONS.get(value) if isinstance(value, str) else None
    reason = join(extra.get("permissionDecisionReason", (data or {}).get("reason")), extra.get("additionalContext"))
    if returncode == 2:
        # Exit 2 always blocks; the message is the JSON reason of a blocking decision, else stderr
        return {"decision": "deny", "reason": (reason if decision == "deny" else "") or stderr.strip() or "Blocked by hook."}
    if returncode != 0 or data is None:
        return None
    if data.get("continue") is False:
        return {"decision": "deny", "reason": join(data.get("stopReason")) or "Stopped by hook."}
    if "updatedInput" in extra and decision != "deny":
        decision = "ask"
        reason = join(reason, "The hook asked to change this tool call's input, which Antigravity "
                              "cannot apply; approving runs the original input.")
    if decision is None:
        return None
    result = {"decision": decision}
    if reason:
        result["reason"] = reason
    return result


def stop_decision(returncode, stdout, stderr):
    """Antigravity Stop output for a Claude Code Stop result (None: let the agent stop)."""
    data = claude_json(stdout)
    if returncode == 2:
        return {"decision": "continue", "reason": stderr.strip() or "A Stop hook asked to keep working."}
    if returncode != 0 or data is None or data.get("continue") is False:
        return None
    if data.get("decision") == "block":
        return {"decision": "continue", "reason": join(data.get("reason")) or "A Stop hook asked to keep working."}
    return None


def hook_marker(kind, payload, spec):
    """Marker file for this hook in this conversation, in the system temp folder.

    kind "stop": the Stop hook kept the conversation running (emulates stop_hook_active).
    kind "once": the SessionStart hook already ran in the conversation (invocationNum restarts
    at 0 on every execution of a conversation, e.g. after a subagent returns).
    """
    key = json.dumps([payload.get("conversationId", ""), spec.get("command"), spec.get("args")])
    name = hashlib.sha1(key.encode("utf-8")).hexdigest()
    return os.path.join(tempfile.gettempdir(), "cc2agy_" + kind, name)


def is_subagent(payload):
    """True when the conversation is a subagent's: Antigravity (agy 1.2.13) writes
    <brain>/<parent>/.system_generated/subagents/<conversationId>.json when it creates one.
    Undocumented; when the file is not found the hook simply runs."""
    conversation = payload.get("conversationId")
    artifacts = payload.get("artifactDirectoryPath")
    if not (isinstance(conversation, str) and conversation and isinstance(artifacts, str) and artifacts):
        return False
    brain = os.path.dirname(os.path.normpath(artifacts))
    pattern = os.path.join(glob.escape(brain), "*", ".system_generated", "subagents", glob.escape(conversation) + ".json")
    return bool(glob.glob(pattern))


def claude_input(mode, payload, project_dir, stop_hook_active=False):
    """The Antigravity hook input plus the fields a Claude Code hook reads."""
    data = dict(payload)
    data.update({
        "session_id": payload.get("conversationId", ""),
        "transcript_path": payload.get("transcriptPath", ""),
        "cwd": project_dir,
        "hook_event_name": EVENT_NAMES[mode],
    })
    if mode == "once":
        data["source"] = "startup"
    if mode == "stop":
        data["stop_hook_active"] = stop_hook_active
    call = payload.get("toolCall")
    if isinstance(call, dict):
        name = call.get("name", "")
        args = call.get("args") if isinstance(call.get("args"), dict) else {}
        renames = TOOL_ARGS.get(name)
        if renames is None:
            # No confirmed equivalent: the Antigravity name and arguments pass as they are
            data["tool_name"] = name
            data["tool_input"] = {k: v for k, v in args.items() if k not in ("toolAction", "toolSummary")}
        else:
            data["tool_name"] = TOOL_NAMES[name]
            data["tool_input"] = {renames[k]: v for k, v in args.items() if k in renames}
            if name == "view_file" and isinstance(args.get("StartLine"), int):
                data["tool_input"]["offset"] = args["StartLine"]
                if isinstance(args.get("EndLine"), int):
                    data["tool_input"]["limit"] = args["EndLine"] - args["StartLine"] + 1
        if mode == "post_tool":
            # Antigravity sends only the tool error, not the tool result
            data["tool_response"] = {"error": payload["error"]} if payload.get("error") else {}
    return data


def report_unsupported(mode, returncode, stdout):
    """Tell (on stderr) what a PostToolUse or Stop hook asked for that Antigravity cannot do."""
    data = claude_json(stdout) or {}
    extra = specific(data)
    asked = [k for k in ("additionalContext", "updatedToolOutput", "updatedMCPToolOutput") if k in extra]
    if mode == "post_tool" and (returncode == 2 or data.get("decision") == "block"):
        asked.insert(0, "block after the tool ran")
    if data.get("continue") is False:
        asked.append("stop the agent")
    if asked:
        note("this hook asked to " + ", ".join(asked) + ", which is not converted for Antigravity.")


def main():
    spec = json.loads(base64.urlsafe_b64decode(sys.argv[1]).decode("utf-8"))
    mode = spec.get("mode", "plain")
    raw_input = sys.stdin.buffer.read()
    try:
        payload = json.loads(raw_input.decode("utf-8")) if raw_input.strip() else {}
    except ValueError:
        payload = {}
    if not isinstance(payload, dict):
        payload = {}
    # Claude Code runs SessionStart and Stop in the main conversation only
    if mode in ("once", "stop") and is_subagent(payload):
        print("{}" if mode == "once" else "", end="")
        return 0
    if mode == "once":
        if payload.get("conversationId"):
            once = hook_marker("once", payload, spec)
            if os.path.exists(once):
                print("{}")
                return 0
            os.makedirs(os.path.dirname(once), exist_ok=True)
            open(once, "w").close()
        elif payload.get("invocationNum", 0) != 0:
            print("{}")
            return 0

    workspaces = payload.get("workspacePaths") or []
    project_dir = workspaces[0] if workspaces else os.getcwd()
    env = dict(os.environ)
    env.update(spec.get("env") or {})
    env["CLAUDE_PROJECT_DIR"] = project_dir

    def fill(text):
        return re.sub(r"\\$\\{?CLAUDE_PROJECT_DIR\\}?", lambda _: project_dir, text)

    command = fill(spec["command"])
    args = spec.get("args")
    hook_input = raw_input
    marker = None
    if mode in EVENT_NAMES and isinstance(payload, dict):
        stop_hook_active = False
        if mode == "stop":
            marker = hook_marker("stop", payload, spec)
            stop_hook_active = os.path.exists(marker)
            if stop_hook_active:
                os.remove(marker)
        hook_input = json.dumps(claude_input(mode, payload, project_dir, stop_hook_active)).encode("utf-8")
    try:
        result = subprocess.run(
            [command] + [fill(a) for a in args] if args is not None else command,
            shell=args is None, input=hook_input, capture_output=True, env=env,
            cwd=project_dir if os.path.isdir(project_dir) else None,
        )
    except OSError as e:
        note(f"cannot start '{command}': {e}")
        return 1 if mode == "plain" else 0
    if result.stderr:
        sys.stderr.buffer.write(result.stderr)
    if mode == "plain":
        sys.stdout.buffer.write(result.stdout)
        return result.returncode
    stdout = result.stdout.decode("utf-8", errors="replace")
    if mode == "pre_tool":
        decision = pre_tool_decision(result.returncode, stdout, result.stderr.decode("utf-8", errors="replace"))
        if decision is not None:
            print(json.dumps(decision))
        return 0
    if mode == "stop":
        decision = stop_decision(result.returncode, stdout, result.stderr.decode("utf-8", errors="replace"))
        if decision is not None:
            os.makedirs(os.path.dirname(marker), exist_ok=True)
            open(marker, "w").close()
            print(json.dumps(decision))
        report_unsupported(mode, result.returncode, stdout)
        return 0
    if mode == "post_tool":
        report_unsupported(mode, result.returncode, stdout)
        return 0
    # Context modes: Claude Code adds stdout to the context only on exit 0; JSON output
    # carries the context in hookSpecificOutput.additionalContext
    output = ""
    if result.returncode == 0:
        data = claude_json(stdout)
        output = join(specific(data).get("additionalContext")) if data is not None else stdout.strip()
        if data is not None and (data.get("decision") == "block" or data.get("continue") is False):
            note("this hook asked to block the prompt, which is not converted for Antigravity.")
    print(json.dumps({"injectSteps": [{"ephemeralMessage": output}]} if output else {}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _python_command() -> str:
    """Interpreter name used to run the generated helper (resolved through PATH)."""
    return "python" if sys.platform == "win32" else "python3"


def _shell_quote(path: str) -> str:
    return f'"{path}"' if " " in path else path


def sanitize_hook_command(command: str, plugin_root: Optional[Path] = None) -> str:
    """Replace ${CLAUDE_PLUGIN_ROOT} in a hook command.

    With plugin_root, the variable becomes that absolute folder (forward slashes, as Claude
    Code substitutes on Windows): Antigravity documents neither the hook working directory
    nor a plugin-root variable, so only an absolute path is reliable. Without plugin_root,
    the legacy relative form ('.') is kept.
    """
    if not command:
        return command
    root = plugin_root.as_posix() if plugin_root is not None else "."
    return _PLUGIN_ROOT_RE.sub(lambda _: root, command)


def _variables_for(plugin_root: Optional[Path], variables: Optional[PluginVariables]) -> PluginVariables:
    """Variables for a conversion; without any, ${CLAUDE_PLUGIN_ROOT} keeps the legacy '.' form."""
    if variables is not None:
        return variables
    return PluginVariables(root=plugin_root if plugin_root is not None else Path("."))


def _build_handler(
    item: Dict[str, Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> Dict[str, Any]:
    """Build one Antigravity handler from a Claude Code handler object.

    A hook runs through the generated hook runner when Antigravity cannot run it as is: a hook
    with a runner mode (context hooks, and PreToolUse, PostToolUse and Stop, whose output is
    translated), an exec-form hook ('args', which must reach the program unquoted), or a hook
    that needs the environment Claude Code exports (CLAUDE_PROJECT_DIR,
    CLAUDE_PLUGIN_OPTION_<KEY>, or plugin scripts reading CLAUDE_*).
    """
    variables = _variables_for(plugin_root, variables)
    raw_command = str(item.get("command", ""))
    raw_args = item.get("args")
    exec_form = isinstance(raw_args, list)
    root = variables.root.as_posix()
    if not exec_form and " " in root and _UNQUOTED_PLUGIN_ROOT_RE.search(raw_command):
        warnings.append(
            f"Hook command uses ${{CLAUDE_PLUGIN_ROOT}} without quotes and the plugin path contains "
            f"spaces ('{root}'); quote it in the source command: {raw_command}"
        )
    where = "hook_exec" if exec_form else "hook_shell"
    command = substitute(raw_command, variables, where, warnings)
    args = [substitute(str(a), variables, "hook_exec", warnings) for a in raw_args] if exec_form else None

    raw_text = " ".join([raw_command, *(str(a) for a in raw_args or [])])
    needs_runner = (
        mode is not None
        or exec_form
        or variables.scripts_read_env
        or bool(RUNTIME_ENV_RE.search(raw_text))
    )
    if needs_runner and helper_dir is not None:
        spec = {
            "mode": mode or "plain",
            "command": command,
            "args": args,
            "env": hook_environment(variables, warnings),
        }
        helper = (helper_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE).as_posix()
        encoded = base64.urlsafe_b64encode(json.dumps(spec).encode("utf-8")).decode("ascii")
        command = f"{_python_command()} {_shell_quote(helper)} {encoded}"
    elif exec_form:
        command = " ".join([_shell_quote(command), *(_shell_quote(a) for a in args)])
        warnings.append(f"Exec-form hook converted to a shell command without the hook runner: {command}")

    handler: Dict[str, Any] = {
        "type": item.get("type", "command"),
        "command": command,
    }
    if "timeout" in item and isinstance(item["timeout"], int):
        handler["timeout"] = item["timeout"]
    return handler


def _is_command_handler(item: Dict[str, Any], warnings: List[str]) -> bool:
    """True for a command hook; other Claude Code hook types (http, prompt, agent, mcp_tool)
    have no Antigravity equivalent and are reported."""
    if "command" in item:
        return True
    kind = item.get("type")
    if isinstance(kind, str) and kind != "command":
        message = f"Skipped '{kind}' hooks: Antigravity runs only command hooks."
        if message not in warnings:
            warnings.append(message)
    return False


def _is_startup_matcher(matcher: Any) -> bool:
    """SessionStart groups apply on startup unless their matcher excludes it."""
    if not matcher or matcher == "*":
        return True
    return bool(re.search(r"\bstartup\b", str(matcher)))


def extract_flat_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    mode: Optional[str] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> List[Dict[str, Any]]:
    """Extract flat handler objects from potentially nested Claude Code hooks lists."""
    handlers: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        if mode == "once" and not _is_startup_matcher(item.get("matcher")):
            warnings.append(
                f"Skipped SessionStart hooks with matcher '{item.get('matcher')}': Antigravity has no "
                "resume, clear, compact or fork event."
            )
            continue
        # Claude Code often nests handlers inside {"hooks": [...]}
        if "hooks" in item and isinstance(item["hooks"], list):
            for sub_item in item["hooks"]:
                if isinstance(sub_item, dict) and _is_command_handler(sub_item, warnings):
                    handlers.append(_build_handler(sub_item, warnings, plugin_root, mode, helper_dir, variables))
        elif _is_command_handler(item, warnings):
            handlers.append(_build_handler(item, warnings, plugin_root, mode, helper_dir, variables))
        elif not isinstance(item.get("type"), str):
            warnings.append(f"Ignored unrecognized hook handler structure: {item}")
    return handlers


def sanitize_matcher(matcher: str) -> str:
    """Map Claude tool names in matchers to Antigravity tool names."""
    if not matcher or matcher == "*":
        return matcher
    mapping = [
        (r"\bMultiEdit\b", "multi_replace_file_content"),
        # Antigravity splits edits into two tools (matchers are regular expressions)
        (r"\bEdit\b", "(?:replace_file_content|multi_replace_file_content)"),
        (r"\bWrite\b", "write_to_file"),
        (r"\bBash\b", "run_command"),
        (r"\bRead\b", "view_file"),
    ]
    cleaned = matcher
    for pat, repl in mapping:
        cleaned = re.sub(pat, repl, cleaned)
    return cleaned


def extract_grouped_handlers(
    items: List[Any],
    warnings: List[str],
    plugin_root: Optional[Path] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
    mode: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Extract grouped matcher handler objects for PreToolUse and PostToolUse."""
    groups: List[Dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        matcher = sanitize_matcher(item.get("matcher", "*"))
        sub_hooks = item.get("hooks", [])
        handlers: List[Dict[str, Any]] = []
        if isinstance(sub_hooks, list):
            for h in sub_hooks:
                if isinstance(h, dict) and _is_command_handler(h, warnings):
                    handlers.append(_build_handler(h, warnings, plugin_root, mode, helper_dir, variables))
        elif _is_command_handler(item, warnings):
            handlers.append(_build_handler(item, warnings, plugin_root, mode, helper_dir, variables))

        if handlers:
            groups.append({
                "matcher": matcher,
                "hooks": handlers,
            })
    return groups


def convert_hooks_data(
    raw_data: Dict[str, Any],
    plugin_name: str = "plugin",
    plugin_root: Optional[Path] = None,
    helper_dir: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
) -> Tuple[Dict[str, Any], List[str]]:
    """Convert raw Claude Code hooks dictionary into Antigravity canonical hooks dictionary.

    Args:
        plugin_root: Absolute folder that ${CLAUDE_PLUGIN_ROOT} stands for (where the
            plugin's scripts live). When omitted, the legacy relative form is used.
        helper_dir: Folder that will hold hooks.json and the generated hook runner.
            When omitted, no command is wrapped.
        variables: What Claude Code plugin variables and userConfig become (overrides plugin_root).
    """
    warnings: List[str] = []

    # If data has a top-level "hooks" wrapper: {"hooks": { ... }}
    hooks_dict = raw_data.get("hooks", raw_data)
    if not isinstance(hooks_dict, dict):
        warnings.append("Root hooks entry is not a dictionary.")
        hooks_dict = {}

    converted_events: Dict[str, Any] = {}

    for raw_event, event_content in hooks_dict.items():
        mapped_event = EVENT_MAPPING.get(raw_event.lower())
        if not mapped_event:
            warnings.append(f"Skipped unsupported hook event: '{raw_event}'.")
            continue

        if raw_event.lower() != mapped_event.lower():
            warnings.append(f"Mapped event '{raw_event}' -> '{mapped_event}'.")

        if not isinstance(event_content, list):
            warnings.append(f"Hook event '{raw_event}' does not contain a list of handlers.")
            continue

        if mapped_event in ("PreToolUse", "PostToolUse"):
            groups = extract_grouped_handlers(
                event_content, warnings, plugin_root, helper_dir, variables, OUTPUT_EVENT_MODES.get(raw_event.lower())
            )
            if groups:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(groups)
                else:
                    converted_events[mapped_event] = groups
        else:
            context_mode = CONTEXT_EVENT_MODES.get(raw_event.lower())
            if context_mode == "always":
                warnings.append(
                    f"'{raw_event}' hooks run before every model invocation in Antigravity, "
                    "not once per user message."
                )
            if context_mode is not None and helper_dir is None:
                warnings.append(
                    f"'{raw_event}' output is not converted to Antigravity context without a destination folder."
                )
            mode = context_mode or OUTPUT_EVENT_MODES.get(raw_event.lower())
            if mode in ("once", "stop") and helper_dir is not None:
                warnings.append(
                    f"'{raw_event}' hooks are skipped in subagent conversations, as in Claude Code, by "
                    "reading an undocumented Antigravity file; if a future Antigravity version changes "
                    "it, these hooks will also run inside subagents."
                )
            handlers = extract_flat_handlers(event_content, warnings, plugin_root, mode, helper_dir, variables)
            if handlers:
                if mapped_event in converted_events:
                    converted_events[mapped_event].extend(handlers)
                else:
                    converted_events[mapped_event] = handlers

    hook_id = f"{plugin_name}-hooks"
    final_hooks_config = {
        hook_id: converted_events
    }
    return final_hooks_config, warnings


def is_settings_file(path: Path) -> bool:
    """True for a Claude Code settings file (settings.json, settings.local.json)."""
    return path.name.lower() in SETTINGS_FILES


def _read_hooks_source(path: Path) -> Any:
    # Settings files are often saved by Windows PowerShell 5.1, which writes a UTF-8 BOM
    encoding = "utf-8-sig" if is_settings_file(path) else "utf-8"
    try:
        with open(path, "r", encoding=encoding) as f:
            return json.load(f)
    except Exception as e:
        raise ValueError(f"Failed to read/parse hooks JSON from {path}: {e}")


def _dedupe_handlers(events: Dict[str, List[Any]]) -> Dict[str, List[Any]]:
    """Drop repeated handlers: Claude Code runs a handler defined in several settings files once."""
    result: Dict[str, List[Any]] = {}
    for event, groups in events.items():
        seen: set = set()
        kept: List[Any] = []
        for group in groups:
            if isinstance(group, dict) and isinstance(group.get("hooks"), list):
                handlers = []
                for handler in group["hooks"]:
                    key = json.dumps([group.get("matcher"), handler], sort_keys=True)
                    if key not in seen:
                        seen.add(key)
                        handlers.append(handler)
                if handlers:
                    kept.append({**group, "hooks": handlers})
            else:
                key = json.dumps(["flat", group], sort_keys=True)
                if key not in seen:
                    seen.add(key)
                    kept.append(group)
        result[event] = kept
    return result


def load_hook_sources(sources: List[Path]) -> Tuple[Optional[Dict[str, Any]], List[str]]:
    """Read Claude Code hooks from hooks.json files and project settings files, joined as
    Claude Code joins settings levels: the hooks of every file add up, and a handler defined
    twice runs once. Settings files must come in precedence order (settings.json, then
    settings.local.json); the last one that sets disableAllHooks decides it.

    Returns ({"hooks": {...}}, warnings), or (None, warnings) when disableAllHooks turns every
    hook off.
    """
    warnings: List[str] = []
    events: Dict[str, List[Any]] = {}
    disabled_by: Optional[Path] = None
    for path in sources:
        data = _read_hooks_source(path)
        if is_settings_file(path):
            if not isinstance(data, dict):
                raise ValueError(f"Settings file {path} does not hold a JSON object")
            ignored = sorted(k for k in data if k not in _SETTINGS_HOOK_KEYS)
            if ignored:
                warnings.append(f"{path.name}: only hooks are converted; not converted: {', '.join(ignored)}.")
            if "disableAllHooks" in data:
                disabled_by = path if data["disableAllHooks"] is True else None
            hooks = data.get("hooks", {})
        else:
            hooks = data.get("hooks", data) if isinstance(data, dict) else data
        if not isinstance(hooks, dict):
            warnings.append(f"Hooks in {path} are not a dictionary; ignored.")
            continue
        for event, groups in hooks.items():
            if isinstance(groups, list):
                events.setdefault(event, []).extend(groups)
            else:
                warnings.append(f"Hook event '{event}' in {path.name} does not contain a list of handlers.")
    if disabled_by is not None:
        warnings.append(f"disableAllHooks is true in {disabled_by}; no hook was converted.")
        return None, warnings
    return {"hooks": _dedupe_handlers(events)}, warnings


def convert_hooks_files(
    sources: List[Path],
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    merge: bool = False,
) -> Tuple[Optional[Path], List[str]]:
    """Convert a project's hooks (hooks.json and .claude/settings*.json, see load_hook_sources)
    into one hook group in dest_dir/hooks.json. Returns (None, warnings) when disableAllHooks
    turns the hooks off; nothing is written then."""
    sources = [p.resolve() for p in sources]
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"

    if dest_file.exists() and not overwrite and not merge:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    raw_data, warnings = load_hook_sources(sources)
    if raw_data is None:
        return None, warnings
    # Every source sits in the project folder, in .claude/ or in hooks/
    variables = standalone_variables(sources[0], dest_dir, scan_scripts=True)
    res, more = write_hooks_data(
        raw_data, dest_dir, plugin_name=plugin_name, overwrite=overwrite, variables=variables, merge=merge
    )
    return res, warnings + more


def convert_hooks_file(
    source_path: Path,
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    merge: bool = False,
) -> Tuple[Path, List[str]]:
    """Read source hooks.json, convert to Antigravity format, and write to dest_dir/hooks.json.

    merge: add the converted hook group to an existing dest_dir/hooks.json (see write_hooks_data).
    """
    source_path = source_path.resolve()
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"

    if dest_file.exists() and not overwrite and not merge:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    try:
        with open(source_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)
    except Exception as e:
        raise ValueError(f"Failed to read/parse hooks JSON from {source_path}: {e}")

    variables = standalone_variables(source_path, dest_dir, scan_scripts=True)
    return write_hooks_data(
        raw_data, dest_dir, plugin_name=plugin_name, overwrite=overwrite, variables=variables, merge=merge
    )


def write_hooks_data(
    raw_data: Dict[str, Any],
    dest_dir: Path,
    plugin_name: str = "plugin",
    overwrite: bool = False,
    plugin_root: Optional[Path] = None,
    variables: Optional[PluginVariables] = None,
    merge: bool = False,
) -> Tuple[Path, List[str]]:
    """Convert already-loaded Claude Code hooks data and write it to dest_dir/hooks.json.

    plugin_root defaults to dest_dir (a packaged plugin keeps its scripts beside hooks.json);
    variables, when given, takes precedence. The hook runner is written to
    dest_dir/cc2agy_hooks/ when any hook needs it.

    With merge, an existing hooks.json is kept: the converted group ('<plugin_name>-hooks')
    is added beside the groups already there, which are never touched; a group with the same
    name needs overwrite. The previous file is saved as hooks.json.cc2agy.bak.
    """
    dest_dir = dest_dir.resolve()
    dest_file = dest_dir / "hooks.json"
    plugin_root = (plugin_root or dest_dir).resolve()

    existing: Optional[Dict[str, Any]] = None
    if merge and dest_file.exists():
        existing = read_json_for_merge(dest_file)
    elif dest_file.exists() and not overwrite:
        raise FileExistsError(f"Destination hooks file already exists: {dest_file}")

    converted_config, warnings = convert_hooks_data(
        raw_data, plugin_name=plugin_name, plugin_root=plugin_root, helper_dir=dest_dir, variables=variables
    )

    dest_dir.mkdir(parents=True, exist_ok=True)
    if existing is not None:
        for hook_id in converted_config:
            if hook_id in existing and not overwrite:
                raise FileExistsError(f"Hook group '{hook_id}' already exists in {dest_file}")
        existing.update(converted_config)
        write_json_with_backup(dest_file, existing)
    else:
        with open(dest_file, "w", encoding="utf-8") as f:
            json.dump(converted_config, f, indent=2, ensure_ascii=False)
            f.write("\n")

    helper_file = dest_dir / CONTEXT_HELPER_DIR / CONTEXT_HELPER_FILE
    if helper_file.as_posix() in json.dumps(converted_config, ensure_ascii=False):
        helper_file.parent.mkdir(parents=True, exist_ok=True)
        helper_file.write_text(CONTEXT_HELPER_SOURCE, encoding="utf-8")

    return dest_file, warnings
